whitelisted_sites = [
    "misbar.com",
    "yoopyup.com",
    "fatabyyano.net",
    "almushahid.net",
    "annir.ly",
    "falso.ly",
    "akhbarmeter.org",
]

labels_map = {
    "refuted": [
        "خطأ",
        "خاطئ",
        "غير صحيح",
        "مش حقيقي",
    ],
    "supported": ["صحيح", "correct", "نص حقيقي"],
    "Not Enough Evidence": [
        "زائف",
        "مزيف",
        "كاذب",
        "خبر كاذب",
        "الادعاء خاطئ",
        "وليدة ذكاء إصطناعي",
        "fake",
    ],
    "Conflicting Evidence/Cherrypicking": [
        "زائف جزئيًا",
        "زائف جزئي",
        "غير صحيح جزئياً",
        "غير صحيح جزئيا",
        "صحيح جزئيًا",
        "صحيح جزئياً",
        "خاطئ جزئيا",
        "خطأ جزئياً",
        "نصف حقيقي",
        "محتوى ناقص",
        "مضلل",
        "مضلّل",
        "اشاعة",
        "مفبرك",
        "سياق ناقص",
        "فيديو معدّل",
        "معدّل",
        "معدل",
        "misleading",
    ],
}
